
test: &test
  adapter: postgresql
  database: prometeo_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: prometeo
  host: localhost
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false
  pool: 5
  timeout: 5000
  encoding: utf8
